[metadata]
name = tdsearch
version = attr: tdsearch.__version__
author = Ivan Cvitic
author_email = cviticivan@gmail.com
license = MIT
license_files = LICENSE
description = Desktop (GUI) for Tabular Data Search powered by xlsxgrep.
url = https://github.com/zazuum/TDsearch
project_urls =
    Source = https://github.com/zazuum/TDsearch
    Tracker = https://github.com/zazuum/TDsearch/issues

long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Environment :: X11 Applications :: Qt
    Environment :: MacOS X
    Environment :: Win32 (MS Windows)
    License :: OSI Approved :: MIT License
    Intended Audience :: End Users/Desktop
    Operating System :: OS Independent
    Programming Language :: Python :: 3
    Topic :: Office/Business
    Topic :: Office/Business :: Financial :: Spreadsheet
    Topic :: Utilities

[options]
packages = tdsearch
install_requires =
    xlsxgrep==0.0.38
    PySide6>=6.0.0
include_package_data = True

[options.package_data]
tdsearch = resources/*

[options.entry_points]
gui_scripts =
    tdsearch = tdsearch.app:main
